export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS'
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE'
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
